name: Dotnet Tests
description: Runs a test project or all test projects in a solution

branding:
  color: green
  icon: check-circle

inputs:
  test-args:
    description: Additional arguments to pass to 'dotnet test'.
    required: false
  build-configuration:
    description: The build configuration to use (defaults to 'Release').
    required: false
    default: Release
  path:
    description: The path to the project or solution to test (defaults to the current directory).
    required: false
    default: .
  skip-build:
    description: Whether or not to skip the build using the '--no-build' flag (defaults to true).
    required: false
    default: 'true'
  display-summary:
    description: Whether or not to display the tests summary (defaults to true) in the job summary.
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Run tests
      uses: EasyDesk/action-dotnet@v1
      with:
        script: |
          ARGS=""
          if [ '${{ inputs.skip-build }}' == "true" ] ; then
            ARGS="${ARGS} --no-build"
          fi
          if [ '${{ inputs.display-summary }}' == "true" ] ; then
            ARGS="${ARGS} --logger 'GitHubActions;report-warnings=false'"
          fi
          dotnet test '${{ inputs.path }}' -c '${{ inputs.build-configuration }}' ${{ inputs.test-args }} ${ARGS}
