name: Dotnet Tests
description: Runs a test project or all test projects in a solution

branding:
  color: green
  icon: check-circle

inputs:
  test-args:
    description: Additional arguments to pass to 'dotnet test'.
    required: false
  build-configuration:
    description: The build configuration to use (defaults to 'Release').
    required: false
    default: Release
  path:
    description: The path to the project or solution to test (defaults to the current directory).
    required: false
  solution:
    description: The solution file to test (defaults to the current directory).
    required: false
  project:
    description: The project file to test (defaults to the current directory).
    required: false
  skip-build:
    description: Whether or not to skip the build using the '--no-build' flag (defaults to true).
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Run tests
      uses: EasyDesk/action-dotnet@v1
      with:
        script: |
          ARGS=""
          if [ '${{ inputs.skip-build }}' == "true" ] ; then
            ARGS="${ARGS} --no-build"
          fi
          if [ -n '${{ inputs.solution }}' ] ; then
            ARGS="${ARGS} --solution '${{ inputs.solution }}'"
          fi
          if [ -n '${{ inputs.project }}' ] ; then
            ARGS="${ARGS} --project '${{ inputs.project }}'"
          fi
          PATH_ARG=""
          if [ -n '${{ inputs.path }}' ] ; then
            PATH_ARG="${{ inputs.path }}"
          fi
          dotnet test "${PATH_ARG}" -c '${{ inputs.build-configuration }}' ${ARGS} ${{ inputs.test-args }}
