name: Dotnet Tests
description: Runs a test project or all test projects in a solution

branding:
  color: green
  icon: check-circle

inputs:
  test-args:
    description: Additional arguments to pass to 'dotnet test'.
    required: false
  build-configuration:
    description: The build configuration to use (defaults to 'Release').
    required: false
    default: Release
  skip-build:
    description: Whether or not to skip the build using the '--no-build' flag (defaults to true).
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Run tests
      uses: EasyDesk/action-dotnet@v1
      with:
        script: |
          ARGS=""
          if [ '${{ inputs.skip-build }}' == "true" ] ; then
            ARGS="${ARGS} --no-build"
          fi
          dotnet test -c '${{ inputs.build-configuration }}' ${ARGS} ${{ inputs.test-args }}
